### ISSUE TITLE
Failed to load example in Excel

### ISSUE THREAD

**Issue by krrrcks** [AccelerationNet/buildnode#4]
Hi, I downloaded the recent version and ran the Excel example. I have put the resutling XML in a file. I can load that file with LibreOffcie but Excel 2010 fails. Am I doing something wrong?

**Comment by dineshbhardwaj** [comment]
thanks Bobby . I was searching for some program which can deal with excel format. I will try this.

**Comment by bobbysmith007** [comment]
I guess this is complete?

**Comment by krrrcks** [comment]
I was the one who brought this issue up. Sorry for not responding in a timely manner. I again tried to open the sample xml file in Excel 2010 an get an error. Excel 2010 does not open the file. Instead a modal dialog is opened and in German (I only have a Excel 2010 in German at hand): "Die Datei '...' kann von Excel nicht geöffnet werden, da das Dateiformat oder die Dateierweiterung ungültig ist. Überprüfen Sie, ob die Datei beschädigt ist und ob die Dateierweiterung dem Dateiformat entspricht." I would translate to: "The file '...' could not be opened because either the file format or the extension is wrong. Please check if the file is damaged or if the file extension matches the file format."

**Comment by krrrcks** [comment]
I get the same message when I try to open it in "Excel Online" via OneDrive.
