### ISSUE TITLE
Does not build if build pathname includes a space

### ISSUE THREAD

**Issue by quicklisp** [AccelerationNet/buildnode#5]
http://report.quicklisp.org/2014-11-26-space/failure-report/buildnode.html has a log - I'm getting this error:

    Unhandled PURI:URI-PARSE-ERROR in thread #<SB-THREAD:THREAD "main
    thread" RUNNING {10049CF5C3}>: Parse error:URI
    "file:///home/quicklisp/quicklisp-controller/space
    dist/build-cache/buildnode/bbf5f6eb4d1a9f2737f26373f5fdca3bb17c3f6e/buildnode-20141126-git/src/xhtml1-transitional.dtd"
    contains illegal character #\ at position 49.

It's not hyper-critical, because things work normally if there are no spaces, but I wanted you to be aware. If you find a good fix, please let me know -- many other projects are affected by similar symptoms.

**Comment by bobbysmith007** [comment]
Sorry to have missed this.  I am looking into it now.  I wish that github had a better screen for actually showing me all the stuff I might be interested in without just scrolling through the timeline (EG: issues and requests for all projects I am associated with).  I couldnt find this ticket in any of the usual views

**Comment by bobbysmith007** [comment]
Ok, the (admittedly hacky) solution was to replace the space character with `"%20"` which is disgusting and also seems like the purvue of puri:parse-uri, but what do I know from urls.  This does allow the system to build correctly. 

78aeed0591cc38d0b49593168de9104b4450021a
